
.PHONY: all clean

all: control geninput genleft genleft_soft genright genright_soft

clean:
	-rm control geninput genleft genleft_soft genright genright_soft

control: control.c

geninput: geninput.c

genleft: genleft.c

genleft_soft: genleft_soft.c

genright: genright.c

genright_soft: genright_soft.c
