
.PHONY: all clean

all: geninput gen_outer gen_left gen_left_soft gen_right gen_right_soft

clean:
	-rm geninput gen_outer gen_left gen_left_soft gen_right gen_right_soft

geninput: geninput.c

gen_outer: gen_outer.c

gen_left: gen_left.c

gen_left_soft: gen_left_soft.c

gen_right: gen_right.c

gen_right_soft: gen_right_soft.c
